config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :pethistories
  resources :pets

  root 'pets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :pets

    def count_pets
        pets.count
    end
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_many :pethistories
    belongs_to :client

    def pet_visits
        pethistories.count
    end

    def pet_weight
        pethistories.pluck(:weight)[0]
    end

    def pet_height
        pethistories.pluck(:height)[0]
    end

    def average_weight
        pethistories.average(:weight)
    end

    def average_height
        pethistories.average(:height)
    end

    def max_weight
        pethistories.pluck(:weight).max
    end

    def max_height
        pethistories.pluck(:height).max
    end

end

app/models/pethistory.rb
class Pethistory < ApplicationRecord
  belongs_to :pet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @pet = Pet.pluck(:name, :id)
    @client = Client.new
    
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email)
    end
end

app/controllers/pethistories_controller.rb
class PethistoriesController < ApplicationController
  before_action :set_pethistory, only: [:show, :edit, :update, :destroy]

  # GET /pethistories
  # GET /pethistories.json
  def index
    @pethistories = Pethistory.all
  end

  # GET /pethistories/1
  # GET /pethistories/1.json
  def show
  end

  # GET /pethistories/new
  def new
    @pethistory = Pethistory.new
    @pets = Pet.pluck(:name, :id)
  end

  # GET /pethistories/1/edit
  def edit
  end

  # POST /pethistories
  # POST /pethistories.json
  def create
    @pethistory = Pethistory.new(pethistory_params)

    respond_to do |format|
      if @pethistory.save
        format.html { redirect_to @pethistory, notice: 'Pethistory was successfully created.' }
        format.json { render :show, status: :created, location: @pethistory }
      else
        format.html { render :new }
        format.json { render json: @pethistory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pethistories/1
  # PATCH/PUT /pethistories/1.json
  def update
    respond_to do |format|
      if @pethistory.update(pethistory_params)
        format.html { redirect_to @pethistory, notice: 'Pethistory was successfully updated.' }
        format.json { render :show, status: :ok, location: @pethistory }
      else
        format.html { render :edit }
        format.json { render json: @pethistory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pethistories/1
  # DELETE /pethistories/1.json
  def destroy
    @pethistory.destroy
    respond_to do |format|
      format.html { redirect_to pethistories_url, notice: 'Pethistory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pethistory
      @pethistory = Pethistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pethistory_params
      params.require(:pethistory).permit(:weight, :height, :description, :pet_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :race, :birthday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pethistories_helper.rb
module PethistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Pets</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.phone %></td>
        <td><%= client.email %></td>
        <td><%= client.count_pets %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Pets:</strong><br>
  <% @client.pets.each do |pet|%>
  <strong>Name:</strong> <%= pet.name %><br>
  <p>Max weight:</p> <%= pet.max_weight %><br>
  <p>Max height:</p> <%= pet.max_height %><br>
  <% end %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pethistories/_form.html.erb
<%= form_with(model: pethistory, local: true) do |form| %>
  <% if pethistory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pethistory.errors.count, "error") %> prohibited this pethistory from being saved:</h2>

      <ul>
        <% pethistory.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :pet_id %>
    <%= form.select :pet_id, options_for_select(@pets) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pethistories/edit.html.erb
<h1>Editing Pethistory</h1>

<%= render 'form', pethistory: @pethistory %>

<%= link_to 'Show', @pethistory %> |
<%= link_to 'Back', pethistories_path %>

app/views/pethistories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pethistories</h1>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th>Height</th>
      <th>Description</th>
      <th>Pet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pethistories.each do |pethistory| %>
      <tr>
        <td><%= pethistory.weight %></td>
        <td><%= pethistory.height %></td>
        <td><%= pethistory.description %></td>
        <td><%= pethistory.pet_id %></td>
        <td><%= link_to 'Show', pethistory %></td>
        <td><%= link_to 'Edit', edit_pethistory_path(pethistory) %></td>
        <td><%= link_to 'Destroy', pethistory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pethistory', new_pethistory_path %>

app/views/pethistories/new.html.erb
<h1>New Pethistory</h1>

<%= render 'form', pethistory: @pethistory %>

<%= link_to 'Back', pethistories_path %>

app/views/pethistories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @pethistory.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @pethistory.height %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pethistory.description %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @pethistory.pet_id %>
</p>

<%= link_to 'Edit', edit_pethistory_path(@pethistory) %> |
<%= link_to 'Back', pethistories_path %>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_field :race %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.text_field :birthday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Race</th>
      <th>Birthday</th>
      <th>Visit</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.race %></td>
        <td><%= pet.birthday %></td>
        <td><%= pet.pet_visits %></td>
        <td><% pet.pethistories.each do |pethistory| %>
            <%= pethistory.description %>
        <% end %>
        </td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Race:</strong>
  <%= @pet.race %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @pet.birthday %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pet.pet_weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @pet.pet_height %>
</p>

<p>
  <strong>Average height:</strong>
  <%= @pet.average_height %>
</p>

<p>
  <strong>Max height:</strong>
  <%= @pet.max_height %>
</p>

<p>
  <strong>Average weight:</strong>
  <%= @pet.average_weight %>
</p>

<p>
  <strong>Max weight:</strong>
  <%= @pet.max_weight %>
</p>


<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>